let products = [
    {
        name: 'Asparagus Jumbo',
        id: 'Item-1',
        type: 'vegetables',
        price: 5,
        image: 'image/products/vegetable/asparagus-jumbo.jpeg',
        quantity: 20,
    },
    {
        name: 'Baby Eggplants',
        id: 'Item-2',
        type: 'vegetables',
        price: 4,
        image: 'image/products/vegetable/baby-eggplants.jpeg',
        quantity: 20,
    },
    {
        name: 'Banana Shallot',
        id: 'Item-3',
        type: 'vegetables',
        price: 3,
        image: 'image/products/vegetable/banana-shallot.jpeg',
        quantity: 20,
    },
    {
        name: 'Beetroot',
        id: 'Item-4',
        type: 'vegetables',
        price: 3,
        image: 'image/products/vegetable/beetroot.jpeg',
        quantity: 20,
    },
    {
        name: 'Cabbage',
        id: 'Item-5',
        type: 'vegetables',
        price: 4,
        image: 'image/products/vegetable/cabbage.png',
        quantity: 20,
    },
    {
        name: 'Carrot',
        id: 'Item-6',
        type: 'vegetables',
        price: 4,
        image: 'image/products/vegetable/carrot.png',
        quantity: 20,
    },
    {
        name: 'Marrow',
        id: 'Item-7',
        type: 'vegetables',
        price: 6,
        image: 'image/products/vegetable/marrow.jpeg',
        quantity: 20,
    },
    {
        name: 'Potato Purple',
        id: 'Item-8',
        type: 'vegetables',
        price: 6,
        image: 'image/products/vegetable/potato-purple.jpeg',
        quantity: 20,
    },
    {
        name: 'Radish Red',
        id: 'Item-9',
        type: 'vegetables',
        price: 3,
        image: 'image/products/vegetable/radish-red.png',
        quantity: 20,
    },
    {
        name: 'Sweet Potato',
        id: 'Item-10',
        type: 'vegetables',
        price: 7,
        image: 'image/products/vegetable/sweet-potato.jpeg',
        quantity: 20,
    },
    {
        name: 'Tomato Bunch',
        id: 'Item-11',
        type: 'vegetables',
        price: 5,
        image: 'image/products/vegetable/tomato-bunch.jpeg',
        quantity: 20,
    },
    {
        name: 'Zucchini Yellow',
        id: 'Item-12',
        type: 'vegetables',
        price: 4,
        image: 'image/products/vegetable/zucchini-yellow.png',
        quantity: 20,
    },
    {
        name: 'Fresh Orange',
        id: 'Item-13',
        type: 'fruits',
        price: 3,
        image: 'image/products/fruits/fresh-orange.png',
        quantity: 20,
    },
    {
        name: 'Grapes Black',
        id: 'Item-14',
        type: 'fruits',
        price: 4,
        image: 'image/products/fruits/grapes-black.jpeg',
        quantity: 20,
    },
    {
        name: 'Lemon',
        id: 'Item-15',
        type: 'fruits',
        price: 4,
        image: 'image/products/fruits/lemon.jpeg',
        quantity: 20,
    },
    {
        name: 'Longan',
        id: 'Item-16',
        type: 'fruits',
        price: 6,
        image: 'image/products/fruits/longan.jpeg',
        quantity: 20,
    },
    {
        name: 'Mango',
        id: 'Item-17',
        type: 'fruits',
        price: 7,
        image: 'image/products/fruits/mango.jpeg',
        quantity: 20,
    },
    {
        name: 'Mangosteen',
        id: 'Item-18',
        type: 'fruits',
        price: 7,
        image: 'image/products/fruits/mangosteen.jpeg',
        quantity: 20,
    },
    {
        name: 'Papaya',
        id: 'Item-19',
        type: 'fruits',
        price: 7,
        image: 'image/products/fruits/papaya.jpeg',
        quantity: 20,
    },
    {
        name: 'Pears Rosemary',
        id: 'Item-20',
        type: 'fruits',
        price: 4,
        image: 'image/products/fruits/pears-rosemary.jpeg',
        quantity: 20,
    },
    {
        name: 'Pomegranate',
        id: 'Item-21',
        type: 'fruits',
        price: 5,
        image: 'image/products/fruits/pomegranate.png',
        quantity: 20,
    },
    {
        name: 'Raspberries',
        id: 'Item-22',
        type: 'fruits',
        price: 8,
        image: 'image/products/fruits/raspberries.jpeg',
        quantity: 20,
    },
    {
        name: 'Red Currant',
        id: 'Item-23',
        type: 'fruits',
        price: 8,
        image: 'image/products/fruits/red-currant.jpeg',
        quantity: 20,
    },
    {
        name: 'Rock Melon',
        id: 'Item-24',
        type: 'fruits',
        price: 8,
        image: 'image/products/fruits/rock-melon.jpeg',
        quantity: 20,
    },
    {
        name: 'Lamb Liver',
        id: 'Item-25',
        type: 'meat',
        price: 15,
        image: 'image/products/meat/hardwicks-lamb-liver.jpeg',
        quantity: 20,
    },
    {
        name: 'Lamb Rack',
        id: 'Item-26',
        type: 'meat',
        price: 17,
        image: 'image/products/meat/lamb-rack.jpeg',
        quantity: 20,
    },
    {
        name: 'Lamb Shank',
        id: 'Item-27',
        type: 'meat',
        price: 17,
        image: 'image/products/meat/lamb-shank.jpeg',
        quantity: 20,
    },
    {
        name: 'Lamb Leg Boneless',
        id: 'Item-28',
        type: 'meat',
        price: 18,
        image: 'image/products/meat/lamb-leg-boneless.jpeg',
        quantity: 20,
    },
    {
        name: 'Black Tiger Prawns',
        id: 'Item-29',
        type: 'seafood',
        price: 22,
        image: 'image/products/seafood/black-tiger-prawns.jpeg',
        quantity: 20,
    },
    {
        name: 'Salmon Fillet',
        id: 'Item-30',
        type: 'seafood',
        price: 22,
        image: 'image/products/seafood/eastco-salmon-fillet.jpeg',
        quantity: 20,
    },
    {
        name: 'Pangasius Fillet',
        id: 'Item-31',
        type: 'seafood',
        price: 22,
        image: 'image/products/seafood/pangasius-fish-fillet.jpeg',
        quantity: 20,
    },
    {
        name: 'Salmon Fillet',
        id: 'Item-32',
        type: 'seafood',
        price: 22,
        image: 'image/products/seafood/salmon-fillet.png',
        quantity: 20,
    },
    {
        name: 'Vannamei Shrimps',
        id: 'Item-33',
        type: 'seafood',
        price: 22,
        image: 'image/products/seafood/vannamei-shrimps.jpeg',
        quantity: 20,
    }
]

let cartLines = [
    {productId: "Item-14", quantity: 3},
    {productId: "Item-22", quantity: 1},
];